name: PR Merged

permissions:
  contents: read
  id-token: write
  packages: read

on:

  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
  # By default, a workflow only runs when a pull_request event's activity type is opened, synchronize, or reopened.
  # We want to run on 'closed' to trigger, but we also have to check if it was merged.
  # That check is: if: github.event.pull_request.merged == true
  pull_request_target:
    types: [ closed ]
    branches:
      - master

jobs:

  npm-packages-pr-create-tag:
    uses: ritterim/public-github-actions/.github/workflows/npm-packages-pr-create-tag-jfrog.yml@v1.16.5
    #uses: ./.github/workflows/npm-packages-pr-create-tag-jfrog.yml
    if: github.event.pull_request.merged == true
    secrets:
      gh_actions_secret_passing_passphrase: ${{ secrets.ACTIONS_SECRET_PASSING_PASSPHRASE }}
      gh_app_private_key: ${{ secrets.RIMDEV_NPM_RELEASES_APP_PRIVATE_KEY }}
    with:
      always_increment_patch_version: true
      gh_app_id: ${{ vars.RIMDEV_NPM_RELEASES_APP_APPID }}
      jfrog_api_base_url: ${{ vars.JFROG_API_BASE_URL }}
      jfrog_artifactory_repository: "${{ vars.JFROG_NPM_PACKAGE_REPO_BASENAME }}-draft"
      jfrog_audit_xray_watch_list: ${{ vars.JFROG_AUDIT_XRAY_WATCH_LIST }}
      jfrog_build_basename: ${{ vars.JFROG_BUILD_BASENAME }}
      jfrog_npm_feed_repo: ${{ vars.JFROG_ARTIFACTORY_VIRTUAL_REPO_NPM }}
      jfrog_npm_package_repo_basename: ${{ vars.JFROG_NPM_PACKAGE_REPO_BASENAME }}
      jfrog_oidc_provider_name: ${{ vars.JFROG_GHA_OIDC_PROVIDER_NAME }}
      npm_package_name: handholdjs
      run_tests: false
